resources:
  limits:
    cpus: 2.0
    memory: 4096

lens:
  db_password: secret
  hostname: localhost
  port: 3030
  frontend_port: 3000
  frontend_url: http://localhost:3000
  default_admin_email: admin@local.test
  default_admin_username: admin
  default_admin_password: admin@local.test
  default_admin_name: Administrator
  local_signed_url_secret: test-secret-key-change-in-production
  smtp_host: ""
  smtp_port: 465
  smtp_user: ""
  smtp_pass: ""
  smtp_from: ""
  vite_app_api_url: ""
  vite_stripe_purchase_peer_url: ""
  additional_envs: []

run_as:
  user: 0
  group: 0

ix_volumes:
  mongodb_data: /opt/tests/mnt/lens/mongodb_data
  uploads: /opt/tests/mnt/lens/uploads

storage:
  mongodb_data:
    type: ix_volume
    ix_volume_config:
      dataset_name: mongodb_data
      create_host_path: true
  uploads:
    type: ix_volume
    ix_volume_config:
      dataset_name: uploads
      create_host_path: true
  additional_storage: []
